name: Bug Report
description: General Issue of DIN SPEC 3105 review.
title: "[DIN SPEC 3105]: General Issue"
labels:
  - din3105
body:
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Please explain what behaviour you expected and why you think this is the correct behaviour.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happens.
      placeholder: Please explain what actually happens. Feel free to provide screenshot if helpful.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: A list of clear and minimal steps to reproduce the problem.
      placeholder: >
        Please make sure you provide a reproducible step-by-step case of how to reproduce the problem,
        as minimally and precisely as possible.
        Keep in mind we do not have access to your deployment.

        Unfortunately non-reproducible issues will have to be closed.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: What operating system(s) are you using?
      multiple: true
      options:
        - Windows
        - macOS
        - Ubuntu
        - Other Linux
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: If your problem needs further explanation, please add more information here.

  - type: markdown
    attributes:
      value: Thank you for completing our form!
